{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ele",
    "module": "lancet-weaver",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lancet-weaver-1.0.7.jar",
          "url": "lancet-weaver-1.0.7.jar",
          "size": 127879,
          "sha512": "5099c2b9ef29627d91f7fe41d223ebbf9dcff521680a52b7b20236c21b5cfa35fc23b14bdfbed91a48d0b95422334a6dd0002c929a60c83c8fbb5425abce96f3",
          "sha256": "405aef1ea71d4e0eadc5b6035d337dee72f32093d574a059b21e218f8e792edc",
          "sha1": "2abeb714ae845e0ee4f98b4794be492fc69184ab",
          "md5": "de4a95aa2fecde55474763232d531532"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.ele",
          "module": "lancet-base",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-jre"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.6"
          }
        }
      ],
      "files": [
        {
          "name": "lancet-weaver-1.0.7.jar",
          "url": "lancet-weaver-1.0.7.jar",
          "size": 127879,
          "sha512": "5099c2b9ef29627d91f7fe41d223ebbf9dcff521680a52b7b20236c21b5cfa35fc23b14bdfbed91a48d0b95422334a6dd0002c929a60c83c8fbb5425abce96f3",
          "sha256": "405aef1ea71d4e0eadc5b6035d337dee72f32093d574a059b21e218f8e792edc",
          "sha1": "2abeb714ae845e0ee4f98b4794be492fc69184ab",
          "md5": "de4a95aa2fecde55474763232d531532"
        }
      ]
    }
  ]
}
