{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ele",
    "module": "lancet-plugin",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lancet-plugin-1.0.7.jar",
          "url": "lancet-plugin-1.0.7.jar",
          "size": 46824,
          "sha512": "7ac9b9e4f21fc62b66a5b53dd5980018683c157d1986ffb818d9e3fd7ec4fa021bf408334c980cdee12004a8266a13532881f854ea6aebeccb4fc9988c63a7e2",
          "sha256": "c2248d1d914c750d9188733bc74e47f88df98aa92f1d622e1c47d46ca3a4ec98",
          "sha1": "3f7c4db515514302c2b0cfc4e83281c9cc9e536c",
          "md5": "a4ba69103e7442352ac73fd169b329c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-jre"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "me.ele",
          "module": "lancet-base",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "me.ele",
          "module": "lancet-weaver",
          "version": {
            "requires": "1.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "lancet-plugin-1.0.7.jar",
          "url": "lancet-plugin-1.0.7.jar",
          "size": 46824,
          "sha512": "7ac9b9e4f21fc62b66a5b53dd5980018683c157d1986ffb818d9e3fd7ec4fa021bf408334c980cdee12004a8266a13532881f854ea6aebeccb4fc9988c63a7e2",
          "sha256": "c2248d1d914c750d9188733bc74e47f88df98aa92f1d622e1c47d46ca3a4ec98",
          "sha1": "3f7c4db515514302c2b0cfc4e83281c9cc9e536c",
          "md5": "a4ba69103e7442352ac73fd169b329c8"
        }
      ]
    }
  ]
}
