{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ele",
    "module": "lancet-base",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lancet-base-1.0.7.jar",
          "url": "lancet-base-1.0.7.jar",
          "size": 6101,
          "sha512": "e99699bd0a90cf779a75922aa0591a1804ebe7d69508f4b011789174e2ca5ac3e0a16b64ea6147638f7ec180b3feae58be765635d3447a990ce786c2586a23c7",
          "sha256": "a5b6e338e7efd4ee19b129783acac898e748be870b926f6e659b3fdb8df64e5a",
          "sha1": "b1a3977c2434f4ab0e9caf2d64cdc87af022e3a8",
          "md5": "82018559642a09a36b00a245b16240b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lancet-base-1.0.7.jar",
          "url": "lancet-base-1.0.7.jar",
          "size": 6101,
          "sha512": "e99699bd0a90cf779a75922aa0591a1804ebe7d69508f4b011789174e2ca5ac3e0a16b64ea6147638f7ec180b3feae58be765635d3447a990ce786c2586a23c7",
          "sha256": "a5b6e338e7efd4ee19b129783acac898e748be870b926f6e659b3fdb8df64e5a",
          "sha1": "b1a3977c2434f4ab0e9caf2d64cdc87af022e3a8",
          "md5": "82018559642a09a36b00a245b16240b2"
        }
      ]
    }
  ]
}
